### ISSUE TITLE
如何设置TemplateParam

### ISSUE THREAD

**Issue by Liesport758** [cn-src/aliyun-sms#1]
aliyun:
    sms:
        accessKeyId: aaaa
        accessKeySecret: bbbb
        signName: ccccc
        templates:
            authentication:
                templateCode: dddd，
配置文件这么设置 的，request.setTemplateParam(Utils.toJsonStr(smsTemplate.getTemplateParam()));这行代码就会报空指针

**Comment by cn-src** [comment]
这是 yml 格式配置, 你检查下缩进
```yaml
aliyun:
  sms:
    accessKeyId: ${aliyun.sms.accessKeyId}
    accessKeySecret: ${aliyun.sms.accessKeySecret}
    signName: ${aliyun.sms.authentication.signName}
    templates:
      authentication:
        templateCode: ${aliyun.sms.authentication.templateCode}
```
